name = "vjl-media-api"
main = "src/index.js"
compatibility_date = "2026-08-24"

[vars]
ALLOWED_ORIGINS = "https://wjbono.github.io"

[images]
binding = "IMAGES"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "vjl-media"

[[d1_databases]]
binding = "DB"
database_name = "vjl-media"
database_id = "d06763c3-049c-404e-b488-8ab821b36d36"

[triggers]
crons = ["*/10 * * * *"]
